<h1 align="center">Task 2 — Model Development Using Logistic Regression</h1>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [29]:
# Data ingestion only 2nd sheet in Excel . So mention that sheet name here .
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Machine_Learning\Dataset\ML_data1.xlsx",sheet_name="Model_Dev")
df

,Student_ID,Department,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Final_Score,Pass_Fail
0,1001,CSE,92,8.0,88,82,8.6,0,6,87,Pass
1,1002,IT,76,5.0,72,68,7.2,1,3,71,Pass
2,1003,ECE,61,3.5,55,52,6.4,3,1,54,Fail
3,1004,AI&DS,95,9.0,94,91,9.1,0,8,93,Pass
4,1005,BBA,68,4.0,61,58,6.8,2,2,60,Pass

### DATA QUALITY CHECK

In [30]:
# to find null values
df.isnull().sum()

Student_ID          0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Internal_Marks      0
Previous_GPA        0
Backlogs            0
Library_Hours       0
Final_Score         0
Pass_Fail           0
dtype: int64

In [31]:
# # to find duplicates
df.duplicated().sum()

np.int64(0)

### FEATURE AND TARGET SELECTION

In [32]:
#  Extracting features without drop
# So  the following is  called as feature selection

X = df[
    ["Attendance",
    "Study_Hours",
    "Assignment_Score",
    "Internal_Marks",
    "Previous_GPA",
    "Backlogs",
    "Library_Hours"
    ]
]

# Select Target
y=df["Pass_Fail"]

In [33]:
# This will show how many Pass and Fail values you have.
y=df["Pass_Fail"]
y.value_counts()

Pass_Fail
Pass    4
Fail    1
Name: count, dtype: int64

In [ ]:
# To view the selected features and target
pd.concat([X,y],axis=1)

,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Pass_Fail
0,92,8.0,88,82,8.6,0,6,Pass
1,76,5.0,72,68,7.2,1,3,Pass
2,61,3.5,55,52,6.4,3,1,Fail
3,95,9.0,94,91,9.1,0,8,Pass
4,68,4.0,61,58,6.8,2,2,Pass

### LABEL_ENCODING

In [11]:
# encoder = LabelEncoder()

In [12]:
# df["Pass_Fail_encoded"]=encoder.fit_transform(df["Pass_Fail"])
# df["Pass_Fail_encoded"]

## Train-Test Split
Split the data into training and testing sets.

In [13]:
# X_train, X_test, y_train, y_test = train_test_split (
#     X,y,
#     test_size = 0.2,
#     random_state = 42
# )

In [14]:
# # To view the shape of train and test sets

# print("X_train:", X_train.shape)
# print("X_test:", X_test.shape)
# print("y_train:", y_train.shape)
# print("y_test:", y_test.shape)

# # X_train (4, 7) → 4 rows × 7 features
# # X_test (1, 7) → 1 row × 7 features
# # y_train (4,) → 4 Pass values
# # y_test (1,) → 1 Fail value

### SCALING
##### Using Standard_Scaler

In [15]:
# num_cols = [
#     "Attendance",
#     "Study_Hours",
#     "Assignment_Score",
#     "Internal_Marks",
#     "Previous_GPA",
#     "Backlogs",
#     "Library_Hours"
# ]

# std_scaler = StandardScaler()

# X_train[num_cols] = std_scaler.fit_transform(X_train[num_cols])
# X_test[num_cols] = std_scaler.transform(X_test[num_cols])

In [16]:
# # To print both train and test set
# print("X_train:")
# print(X_train[num_cols].head())

# print("\nX_test:")
# print(X_test[num_cols].head())

## Build Logistic Regression Model
##### (i) Model_Building & Training

In [17]:
# log_model = LogisticRegression()

# # Trains the model using:

# # X_train → input/features (attendance, study hours, marks, etc.)
# # y_train → actual Final_Score


# # .fit() = teach the model using training data

# log_model.fit(X_train, y_train)

### (ii). Model Prediction
##### For testing model

In [18]:
# y_pred=log_model.predict(X_test)
# y_pred

In [19]:
# # To cross compare the values
# print("Actual: " ,y_test.values)
# print("Predict: " , y_pred)

##### For training model

In [20]:
# y_pred=log_model.predict(X_train)
# y_pred

In [21]:
# To cross compare the values
# print("Actual: " ,y_train.values)
# print("Predict: " , y_pred)

### (i). Accuracy Score Metrics

In [22]:
# # Overall correct prediction is known as accuracy
# # It is a classification metrics

# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy Score:", accuracy)

### (ii). Confusion Matrix

In [23]:
# # This matrix is used in classification because  (pass or fail)
# # Here it doesn't shown properly. Because I have 1 test case,So leave this matrix
# Conf_matrix = confusion_matrix(y_test, y_pred,labels=["Fail", "Pass"])
# print("Conf_matrix:" ,Conf_matrix)

### (iii). Classification_report Matirx

In [24]:
# print(classification_report(y_test, y_pred,labels=["Fail", "Pass"],zero_division=0))

# # Recall: Out of all actual positive cases, how many did the model correctly predict? (when:  in sensitive conditions it used )
# # Recall=TP / (TP + FN)

# # Precision: Out of all cases predicted as positive, how many were actually positive?
# # Precision=TP / (TP + FP)

# # Pass support = 2 (2 students actually passed)

# # Fail support = 1 (1 student actually failed)

# # Remember: Support counts the actual results, not the model's predictions.

### Compare Actual vs Predicted

In [25]:
# results = pd.DataFrame({
#     "Actual": y_test,
#     "Predicted": y_pred
# })

# print(results)

In [26]:
# import matplotlib.pyplot as plt

# plt.bar(["Actual", "Predicted"], [1,0],color="Brown")

# plt.title("Logistic Regression - Actual vs Predicted")
# plt.ylabel("Class")
# plt.show()

In [27]:

# # Convert Pass/Fail to 0/1 for plotting
# y_actual = np.where(y_test == "Pass", 1, 0)

# # Create x values for sigmoid curve
# x = np.linspace(-10, 10, 100)

# # Sigmoid function
# y = 1 / (1 + np.exp(-x))

# # Sigmoid curve
# plt.plot(x, y, label="Sigmoid Curve",color="Purple")

# # Actual data points
# plt.scatter(range(len(y_actual)), y_actual, label="Actual Data",color="Red")

# # Classification threshold
# plt.axhline(0.5, linestyle="--", label="Threshold = 0.5",color="Green")

# plt.title("Logistic Regression - Sigmoid Curve")
# plt.xlabel("Input")
# plt.ylabel("Probability")
# plt.legend()
# plt.grid(True)

# plt.show()

In [ ]:
# train_mse = mean_squared_error(y_train, y_pred)
# test_mse = mean_squared_error(y_test, y_pred)

# print("Training MSE:", train_mse)
# print("Testing MSE:", test_mse)

NameError: name 'y_train' is not defined

In [ ]:
#