In [1]:
import pandas as pd

from sklearn.linear_model import LogisticRegression

# Imports Decision Tree, which makes predictions using a tree-like structure of decisions.
from sklearn.tree import DecisionTreeClassifier

# Imports Random Forest, which combines multiple decision trees to make predictions.
from sklearn.ensemble import RandomForestClassifier

# Imports a report that evaluates model performance using precision, recall, F1-score, and support.
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split

### IMPORT DATA

In [2]:
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Machine_Learning\Dataset\ML_data1.xlsx",sheet_name="Model_Dev")
df

,Student_ID,Department,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Final_Score,Pass_Fail
0,1001,CSE,92,8.0,88,82,8.6,0,6,87,Pass
1,1002,IT,76,5.0,72,68,7.2,1,3,71,Pass
2,1003,ECE,61,3.5,55,52,6.4,3,1,54,Fail
3,1004,AI&DS,95,9.0,94,91,9.1,0,8,93,Pass
4,1005,BBA,68,4.0,61,58,6.8,2,2,60,Pass

### To check null values

In [3]:
df.isnull().sum()

Student_ID          0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Internal_Marks      0
Previous_GPA        0
Backlogs            0
Library_Hours       0
Final_Score         0
Pass_Fail           0
dtype: int64

### To check duplicates

In [4]:
df.duplicated().sum()

np.int64(0)

### Feature and target selection

In [5]:
#  the following is  called as feature selection
X = df[
    ["Attendance",
    "Study_Hours",
    "Assignment_Score",
    "Internal_Marks",
    "Previous_GPA",
    "Backlogs",
    "Library_Hours"
    ]
]

# Select Target
y=df["Pass_Fail"]

In [6]:
# To view the selected features and target
pd.concat([X,y],axis=1)

,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Pass_Fail
0,92,8.0,88,82,8.6,0,6,Pass
1,76,5.0,72,68,7.2,1,3,Pass
2,61,3.5,55,52,6.4,3,1,Fail
3,95,9.0,94,91,9.1,0,8,Pass
4,68,4.0,61,58,6.8,2,2,Pass

##### Splitting Data into Training and Testing Sets

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

(4, 7)
(1, 7)

##### Defining and Initializing the Machine Learning Models

In [8]:
models={

    # "Logistic Regression": – Name used to identify the model in the dictionary.
    #  LogisticRegression(max_iter=1000) – Creates the model; max_iter=1000 allows up to 1,000 iterations to find a solution.
    
    "Logistic Regression" : LogisticRegression(max_iter=1000),

    # DecisionTreeClassifier( – Initializes a Decision Tree classification algorithm.
    "Decision Tree" : DecisionTreeClassifier(
        max_depth=4,random_state=42
    ),
    "RandomForest" : RandomForestClassifier(
        
        # n_estimators=100 – Uses 100 decision trees.
        n_estimators=100,random_state=42
    )
}

### Model Training and Evaluation

In [9]:
# Loops through each model in the dictionary and gets its name and model object.
for name, model in models.items():
   
   model.fit(X_train,y_train)
   predictions = model.predict(X_test)
   print(f"\n{name}")
   print(classification_report(
    y_test, predictions, zero_division=0
    ))

Logistic Regression
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1


Decision Tree
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1


RandomForest
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1